crudproject/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
]

employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    emp_id = models.CharField(max_length=20)
    emp_name = models.CharField(max_length=100)
    emp_designation = models.CharField(max_length=50)
    emp_contact = models.CharField(max_length=20)
    emp_email = models.CharField(max_length=20)
    class Meta:
        db_table = "employee"

employee/forms.py
from django import forms
from employee.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

employee/views.py
from django.shortcuts import render, redirect
from employee.models import Employee
from employee.forms import EmployeeForm
# Create your views here.

# REVIEW: this is add method
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,'employee/index.html', { 'form' : form })

def show(request):
    employees = Employee.objects
    return render(request,'employee/show.html', { 'employees' : employees })

def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'employee/edit.html', { 'employee' : employee } )

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        try:
            form.save()
            return redirect('/show')
        except:
            pass
    return render(request, 'employee/edit.html', { 'employee' : employee })

def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')

employee/templates/employee/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Details</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body >

  <div class="container">
    <br>

  <div class="form-group row">
    <div class="col-sm-12">
      <h3>Enter Details</h3>
    </div>
  </div>
  <hr/>
    <br>
  <form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="form-group row">
      <label for="inputEmpId" class="col-sm-2 col-form-label">Employee ID</label>
      <div class="col-sm-6">
        <input type="text" name="emp_id" id="id_emp_id" max_length="20"  value="{{employee.emp_id}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpName" class="col-sm-2 col-form-label">Employee Name</label>
      <div class="col-sm-6">
        <input type="text" name="emp_name" id="id_emp_name" max_length="20"  value="{{employee.emp_name}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpEmail" class="col-sm-2 col-form-label">Employee Email</label>
      <div class="col-sm-6">
        <input type="text" name="emp_email" id="id_emp_email" max_length="20"  value="{{employee.emp_email}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpContact" class="col-sm-2 col-form-label">Employee Contact</label>
      <div class="col-sm-6">
        <input type="text" name="emp_contact" id="id_emp_contact" max_length="20"  value="{{employee.emp_contact}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpDesignaton" class="col-sm-2 col-form-label">Employee Designation</label>
      <div class="col-sm-6">
        <input type="text" name="emp_designation" id="id_emp_designation" max_length="20"  value="{{employee.emp_designation}}">
      </div>
    </div>

    <br>
    <hr/>
      <br>
      <div class="form-group row">
        <label for="inputEmpDesignaton" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-6">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>

</form>
</div>
</body>
</html>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

employee/templates/employee/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Details</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body >

  <div class="container">
    <br>

  <div class="form-group row">
    <div class="col-sm-12">
      <h3>Enter Details</h3>
    </div>
  </div>
  <hr/>
    <br>
  <form method="POST" class="post-form" action="/employee">
    {% csrf_token %}
    <div class="form-group row">
      <label for="inputEmpId" class="col-sm-2 col-form-label">Employee ID</label>
      <div class="col-sm-6">
        {{ form.emp_id }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpName" class="col-sm-2 col-form-label">Employee Name</label>
      <div class="col-sm-6">
        {{ form.emp_name }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpEmail" class="col-sm-2 col-form-label">Employee Email</label>
      <div class="col-sm-6">
        {{ form.emp_email }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpContact" class="col-sm-2 col-form-label">Employee Contact</label>
      <div class="col-sm-6">
        {{ form.emp_contact }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmpDesignaton" class="col-sm-2 col-form-label">Employee Designation</label>
      <div class="col-sm-6">
        {{ form.emp_designation }}
      </div>
    </div>

    <br>
    <hr/>
      <br>
      <div class="form-group row">
        <label for="inputEmpDesignaton" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-6">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>

</form>
</div>
</body>
</html>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

employee/templates/employee/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<table class="table">
    <thead class="thead-light">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Employee Designation</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees.all %}
    <tr>
        <td>{{ employee.emp_id }}</td>
        <td>{{ employee.emp_name }}</td>
        <td>{{ employee.emp_email }}</td>
        <td>{{ employee.emp_contact }}</td>
        <td>{{ employee.emp_designation }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" ></span></a>
            <a href="/delete/{{ employee.id }}"><span class="glyphicon glyphicon-trash"></span></a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/employee" class="btn btn-primary">Add New Record</a></center>
</body>
</html>